### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by 8mylez** [8mylez/sputnik-todo#1]
We need to discuss the UI of our ToDo App.

Any suggestions? @cytzix @vschaefer1

**Comment by 8mylez** [comment]
Maybe @vschaefer1 could make an draft for the UI. We need a place for the buttons and a place for the todo list. 

Maybe this image is helpful for you:

![fcedcc6abd4aa83dbc2faaef6ff8e1ee](https://cloud.githubusercontent.com/assets/3687475/15273342/09ee67e4-1a96-11e6-93a9-a2cae71e3a37.jpg)

**Comment by cytzix** [comment]
![bildschirmfoto 2016-05-15 um 12 47 08](https://cloud.githubusercontent.com/assets/19369959/15273486/42808312-1a9b-11e6-9787-fcd2ba98f8e1.png)
Maybe you could create something like that for the first draft, but with more buttons and a better design?

**Comment by vschaefer1** [comment]
[skitze.pdf](https://github.com/8mylez/sputnik-todo/files/265306/skitze.pdf)

**Comment by vschaefer1** [comment]
look at that draft, do you want it like that? 
Sorry, i have some problems with connecting html to css

**Comment by 8mylez** [comment]
Hmm, the pdf is not working for me. Could you reupload it?

**Comment by vschaefer1** [comment]
i uploadet it in the issue "UI HTML"
