### ISSUE TITLE
UI in HTML

### ISSUE THREAD

**Issue by 8mylez** [8mylez/sputnik-todo#10]
When #1 is done, we need that draft in HTML Code.

**Comment by vschaefer1** [comment]
im working on that

**Comment by 8mylez** [comment]
Maybe we should finish #1 before. What do you think @cytzix @vschaefer1 ?

I mean, before coding it in HTML we need a draft of the user interface. Do you need help?

**Comment by vschaefer1** [comment]
![skitze](https://cloud.githubusercontent.com/assets/19369964/15277234/4e26aaee-1afe-11e6-920f-8892830b4d04.jpg)

**Comment by vschaefer1** [comment]
i made some changes on the master branch, and saw then, that there are some pulls. now i can't pull.

**Comment by 8mylez** [comment]
Yeah, that because need to "commit" your changes first. Then "pull" them from the origin.

**Comment by vschaefer1** [comment]
ok, ill try

**Comment by vschaefer1** [comment]
yeah, it worked
