### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by 8mylez** [8mylez/sputnik-todo#2]
What do you think about this logo? @cytzix @vschaefer1 

![screenshot 2016-05-15 10 22 32](https://cloud.githubusercontent.com/assets/3687475/15272865/f462d234-1a86-11e6-8ffb-66028d913c7d.png)

**Comment by cytzix** [comment]
Looks great, however I would change the color to red - do you agree? Black seems not to be very inviting.

**Comment by vschaefer1** [comment]
i like black more

**Comment by vschaefer1** [comment]
o would make the logo and the text closer to each other

**Comment by 8mylez** [comment]
What about a red hover? I think it is a good compromise.

**Comment by cytzix** [comment]
I agree to keep the logo black, however lets add more color to the "Sputnik" itself like at Google each charakter with different color. OK?

**Comment by cytzix** [comment]
I'd say we test at least the different color characters and if you still do not agree, we can discard that change, ok?

**Comment by 8mylez** [comment]
Sounds great! Just implement it and then we'll see.

**Comment by cytzix** [comment]
Viktor, I'll assign you for that task ;-)

**Comment by vschaefer1** [comment]
i will do it

**Comment by vschaefer1** [comment]
![f462d234-1a86-11e6-8ffb-66028d913c7d-2](https://cloud.githubusercontent.com/assets/19369964/15273129/3c24ed6a-1a90-11e6-87eb-938c937405e0.png)
